name: Frontend publishing

on:
  push:
    branches:
      - 'master'

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out
              uses: actions/checkout@v3
      
            - name: Publishing to GitHub Pages
              uses: rayluo/github-pages-overwriter@v1.3
      
              with:
                source-directory: webapp      
                target-branch: gh-pages